spring.application.name=secure-file-sharing
spring.datasource.url=jdbc:mysql://localhost:3306/secure_file_sharing?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Kolkata
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=16072001
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

# File upload configuration
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
spring.servlet.multipart.enabled=true
